plugins {
    id 'com.android.application'
}
android {
    compileSdk 34
    namespace "com.djomlar.reardisplayfix2"
    defaultConfig {
        applicationId "com.djomlar.reardisplayfix2"
        minSdk 30
        targetSdk 34
        versionCode 6
        versionName "1.1.4"
    }
buildTypes {
        release {
            // Skip lintVital task
            lintOptions {
                checkReleaseBuilds false
                abortOnError false
            }
            // or for AGP 8.x+ syntax
            lint {
                checkReleaseBuilds false
                abortOnError false
            }
        }
    }
}
dependencies {
    compileOnly files('libs/LSPosed_API.jar')
}
repositories {
    flatDir {
        dirs 'libs'
    }
}